### ISSUE TITLE
用户退出登陆token不会失效

### ISSUE THREAD

**Issue by zhaoyang0415** [sunnj/story-admin#1]
您好，现有一个疑问，在用户登陆后，主动退出。继续带有token访问资源时。仍然是可以访问到受保护的资源。这可能会导致用户登陆一次可以无限制的进行token刷新操作。token对受保护的资源的限制应该只对已登陆未过期用户起作用才可以吧？
![image](https://user-images.githubusercontent.com/14163649/59673175-617a5b80-91f3-11e9-8962-1b67cf2903c7.png)
![image](https://user-images.githubusercontent.com/14163649/59673195-6dfeb400-91f3-11e9-8e35-da7239ecbdf6.png)

**Comment by sunnj** [comment]
用户主动登出时，前端应当清除临时存储的Token，同时后端应当删除缓存，当再次请求时，不会携带有token，同时后端会判断是未登录状态，返回401，前端跳转到登陆。
项目前端地址也已经提交，供参考 https://github.com/sunnj/story-admin-console

**Comment by sunnj** [comment]
登出后未删除缓存导致，已经修复
