### ISSUE TITLE
token只要未过期就可使用

### ISSUE THREAD

**Issue by hanzhenchaoGit** [sunnj/story-admin#2]
token只要是在有效期内就能使用 正常应该是一个用户只有一个token能用才对 是否应该将当前token放入redis 每次请求来不止要jwt验证token有效性 还应该与redis里的对比 同时满足才可以 避免伪造的token

**Comment by sunnj** [comment]
已经修复。登录时在redis中记录时间戳，每次颁发新的token时会校验时间戳，一致则颁发，不一致则报告token失效。
