### ISSUE TITLE
应该考虑增加老token失效的机制

### ISSUE THREAD

**Issue by bradwang** [sunnj/story-admin#3]
这个方案有点问题，这个redis锁只能锁住并发，如果持有原有token的请求时间上有一定间隔，则每次请求都会刷新一次token。最主要的问题是，这不能拦住恶意持有老的token的人再次做请求，并得到新的token。

**Comment by sunnj** [comment]
已修复。
在登录时记录时间戳到redis，在检测需要更新令牌时，获取到锁，并校验token的时间戳与redis是否一致，一致则颁发新的token，同时更新redis中的时间戳。
当再次使用旧的token发起请求时，发现需要更换token，则重新获取锁，并校验时间戳，发现时间戳不一致，则判定为token无效。
