### ISSUE TITLE
请求token校验问题

### ISSUE THREAD

**Issue by hanzhenchaoGit** [sunnj/story-admin#4]
![image](https://user-images.githubusercontent.com/20226394/60960131-017f5c80-a33c-11e9-86ac-af49451879a2.png)
校验token有效的代码是不是应该放到preHandle里，作为进入controller之前的一个拦截，如果放在isAllow函数进行校验 那么在返回401的时候是不是会跟controller请求里返回数据时servlet获取writer的时候发生冲突 会报异常 而且即使isAllow返回false 但是依旧会进入目标controller，而放在preHanle里如果校验不通过就不会再进入controller

**Comment by sunnj** [comment]
preHandle其实是PathMatchingFilter中的方法，主要作用是用于匹配url规则，并且这里的执行顺序是：
preHandle->isAccessAllowed->isLoginAttempt->executeLogin
如果你直接用重写preHandle，那么可能会导致你在shiroConfig中配置的拦截器规则失效，致使所有的请求都需要isLoginAttempt通过才可以执行。而这里我需要匿名可以访问一些公开的API接口，如登录等，preHandle就不适用。
而且代码中 isAccessAllowed 返回false并不会继续执行controller。

**Comment by hanzhenchaoGit** [comment]
我把登陆url在shiro配置anon是可以正常跳过校验的

**Comment by lihephd** [comment]
这个地方有问题，当我的 getSubject(request, response).login(jwtToken)里面抛异常之后，会用response401把异常抛出，此时Caused by: java.lang.IllegalStateException: getWriter() has already been called for this response 会出现这个异常，貌似就是上面的哥们说的那个意思，而且出异常之后doGetAuthenticationInfo会被运行两次，我不知道怎么解决，问题描述不是特别好描述
