### ISSUE TITLE
preHandle其实是PathMatchingFilter中的方法，主要作用是用于匹配url规则，并且这里的执行顺序是：

### ISSUE THREAD

**Issue by lihephd** [sunnj/story-admin#6]
preHandle其实是PathMatchingFilter中的方法，主要作用是用于匹配url规则，并且这里的执行顺序是：
preHandle->isAccessAllowed->isLoginAttempt->executeLogin
如果你直接用重写preHandle，那么可能会导致你在shiroConfig中配置的拦截器规则失效，致使所有的请求都需要isLoginAttempt通过才可以执行。而这里我需要匿名可以访问一些公开的API接口，如登录等，preHandle就不适用。
而且代码中 isAccessAllowed 返回false并不会继续执行controller。

_Originally posted by @sunnj in https://github.com/sunnj/story-admin/issues/4#issuecomment-510765090_

**Comment by lihephd** [comment]
这个地方有问题，当我的  getSubject(request, response).login(jwtToken)里面抛异常之后，会用response401把异常抛出，此时Caused by: java.lang.IllegalStateException: getWriter() has already been called for this response  会出现这个异常，貌似就是上面的哥们说的那个意思，而且出异常之后doGetAuthenticationInfo会被运行两次，我不知道怎么解决，问题描述不是特别好描述

**Comment by sunnj** [comment]
父类BasicHttpAuthenticationFilter中的onAccessDenied方法中是会再次调用executeLogin，而我们在JwtFilter中只重写了isAccessAllowed，并没有重写onAccessDenied，是会导致executeLogin被重新调用。我重写了onAccessDenied，代码已经提交，你可以重新pull测试下。

**Comment by lihephd** [comment]
这下我的疑问就全解决了。我没有看源码。之前不知道会调用isAllowdenied，能加个好友吗？以后有什么问题相互探讨一下
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sunnj87 <notifications@github.com>
发送时间: 2019年8月12日 15:22
收件人: sunnj/story-admin <story-admin@noreply.github.com>
抄送: lihephd <897197058@qq.com>, Author <author@noreply.github.com>
主题: 回复：[sunnj/story-admin] preHandle其实是PathMatchingFilter中的方法，主要作用是用于匹配url规则，并且这里的执行顺序是： (#6)




父类BasicHttpAuthenticationFilter中的onAccessDenied方法中是会再次调用executeLogin，而我们在JwtFilter中只重写了isAccessAllowed，并没有重写onAccessDenied，是会导致executeLogin被重新调用。我重写了onAccessDenied，代码已经提交，你可以重新pull测试下。
